//FILM types
export const GET_FILMS_TVSERIES = 'GET_FILMS_TVSERIES';
export const GET_FILMS_MOVIES = 'GET_FILMS_MOVIES';
export const GET_FILMS_DETAILS = 'GET_FILMS_DETAILS';
export const LOADING_TRUE = 'LOADING_TRUE';
export const GET_FILMS_ALL = 'GET_FILMS_ALL';
export const ERROR = 'ERROR';
export const DELET_FILM_SUCCESS = 'DELET_FILM_SUCCESS';
export const DELET_FILM_FAIL = 'DELET_FILM_FAIL';

export const POST_MOVIE_FAIL = 'POST_FILM_FAIL';
export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const ALL_USER = 'ALL_USER';

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

export const POST_PAYMENT_SUCCSESS = 'POST_PAYMENT_SUCCSESS';
export const POST_PAYMENT_FAIL = 'POST_PAYMENT_FAIL';
export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS';
export const GET_ALL_TRANSACTION_FAIL = 'GET_ALL_TRANSACTION_FAIL';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_FAIL = 'EDIT_TRANSACTION_FAIL';

export const POST_EPISODES_SUCCESS = "POST_EPISODES_SUCCESS";
export const POST_EPISODES_FAIL = "POST_EPISODES_FAIL";
export const POST_EPISODESTV_SUCCESS = "POST_EPISODESTV_SUCCESS";
export const POST_EPISODESTV_FAIL = "POST_EPISODESTV_FAIL";

export const EDIT_UNSUBS_SUCCESS = "EDIT_UNSUBS_SUCCESS";
export const EDIT_UNSUBS_FAIL = "EDIT_UNSUBS_FAIL";